name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  first-workflow:
    runs-on: windows-latest

    steps:
      - name: First Step
        run: |
          echo "Hello World!"
          echo "Hello Again!"
