name: CronJob Workflow

on:
  schedule:
    - cron: "*/5 * * * *" #Runs in every 5 minits

jobs:
  first-workflow:
    runs-on: windows-latest

    steps:
      - name: Cronjob Steps
        run: |
          echo "Hello Cron Job"
          echo "Hello cron job again!"
